# Generated by Django 4.2.7 on 2023-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longtitude", models.FloatField()),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("perce", models.IntegerField()),
            ],
        ),
    ]
